apiVersion: v1
kind: Service
metadata:
  name: build-deploy-python-web
  namespace: pyhon-web-fe
  labels:
    app.kubernetes.io/name: build-deploy-python-web
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: build-deploy-python-web
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000